### ISSUE TITLE
why make da youtube thumbnaisl but doesnt make thumbnaisl for jurst normal image links 

### ISSUE THREAD

**Issue by dotflac** [knivey/lolbot#1]
wtf like surely ts harder to amke thumnabnsilf from youtube than tod make one from a umgur .com link liek wtf what were u thinkin u fuckin fish

**Comment by rj1** [comment]
pls do the needful

**Comment by rj1** [comment]
tired of Not Getting Helped @dotflac

**Comment by knivey** [comment]
Done

**Comment by dotflac** [comment]
new phone who dis?
